AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  LogRetention:
    Type: Number
    Default: 14

Resources:
  ZendeskAuthorizationLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-zendesk-authorization-lambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  ZendeskAuthorizationLambdaName:
    Value: !Sub "${ProjectName}-zendesk-authorization-lambda"
